// Generated by Wrangler by running `pnpm cf-typegen`
// Run `pnpm cf-typegen` after changing wrangler.jsonc bindings to regenerate.
declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
		KV: KVNamespace;
		R2: R2Bucket;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		BETTER_AUTH_URL: string;
		ALLOWED_ORIGINS: string;
	}
}
interface CloudflareBindings extends Cloudflare.Env {}
